const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const nav=$('.nav'),progress=$('.progress i'),toTop=$('.to-top'),menu=$('.mobile-menu'),toggle=$('.menu-toggle');
function onScroll(){const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max?y/max*100:0}%`;nav.classList.toggle('scrolled',y>24);toTop.classList.toggle('visible',y>500);let current='home';$$('main section[id]').forEach(s=>{if(y>=s.offsetTop-140)current=s.id});$$('.nav nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${current}`))}addEventListener('scroll',onScroll,{passive:true});onScroll();
toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.classList.toggle('open',open);toggle.setAttribute('aria-expanded',open)});$$('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.classList.remove('open')}));toTop.onclick=()=>scrollTo({top:0,behavior:'smooth'});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
const modal=$('.modal'),programModal=$('.program-modal'),form=$('form'),closeModal=m=>{m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow=''};function openModal(program){modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';if(program){const select=$('[name=program]',modal);if([...select.options].some(o=>o.value===program))select.value=program}setTimeout(()=>$('#modal-title',modal).focus?.(),50)}
$$('[data-modal]').forEach(b=>b.addEventListener('click',()=>{closeModal(programModal);openModal(b.dataset.program)}));$$('.close').forEach(b=>b.addEventListener('click',()=>closeModal(b.closest('.modal'))));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal.open').forEach(closeModal)});
const info={AI:['Artificial Intelligence','A practical introduction to AI, Generative AI, prompt engineering and responsible creation.'], 'Digital Marketing':['Digital Marketing','A practical foundation in digital strategy, content, search, social media and analytics.'], 'Robotics & Automation':['Robotics & Automation','Explore physical computing, sensors, Arduino and automation through hands-on projects.'], 'IT & Agile Skills':['IT & Agile Skills','Build confidence with modern IT foundations, agile thinking and team workflows.']};$$('[data-program]').forEach(b=>b.addEventListener('click',e=>{if(b.hasAttribute('data-modal'))return;const [title,copy]=info[b.dataset.program]||info.AI;$('.program-title').textContent=title;$('.program-info').textContent=copy;programModal.classList.add('open');programModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));
function validate(input){const bad=!input.checkValidity();input.classList.toggle('invalid',bad);return !bad}$$('input[required],select[required]',form).forEach(input=>input.addEventListener('blur',()=>validate(input)));form.addEventListener('submit',e=>{e.preventDefault();const valid=$$('input[required],select[required]',form).every(validate);if(!valid){$('input.invalid,select.invalid',form)?.focus();return}form.style.display='none';$('.success',modal).classList.add('show')});$('.close-success').onclick=()=>{closeModal(modal);setTimeout(()=>{form.reset();form.style.display='';$('.success',modal).classList.remove('show')},300)};
